### GET /subscribers
GET http://localhost:3000/subscribers

### POST /subscriber
POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "userName":"José Silva",
    "userChannel": "hcodebrasil"
}

### GET /subscribers/:id
GET http://localhost:3000/subscribers/6073be823ab66b50a409ccb2

### DELETE /subscribers/:id
DELETE http://localhost:3000/subscribers/6073c322c3a3c732acae11bc

